name: Build and publish game on github pages

on:
  push:
    branches: [ $default-branch, master, ci/ci ]
  pull_request:
    branches: [ $default-branch, master, ci/ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build:prod
        mkdir build
        cp -r dist build/
        cp -r textures build/
        cp -r assets build/
        cp ComesAdventureWorld1-Map.json build/
        cp ComesAdventureWorld1-Tileset.json build/
        cp index.html build/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: game-gh-pages
        FOLDER: build
        CLEAN: true
        SINGLE_COMMIT: true